apiVersion: {{ .Values.apiVersion.secret }}
kind: Secret
metadata:
  name: {{ .Values.secret_name }}
data:
  encryption_key: {{ .Values.encryption_key | b64enc }}

---

apiVersion: {{ .Values.apiVersion.secret }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
data:
  tls.crt: {{ .Values.ingress.tls.cert | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}


---

apiVersion: {{ .Values.apiVersion.secret }}
kind: Secret
metadata:
  name: {{ .Values.splunkUF.secretName }}
data:
  password: {{ .Values.splunk_pwd | b64enc }}
