###################### Filebeat Configuration Example #########################
CONFIG: /etc/filebeat/
FILEBEAT_LOGS_DIR: hostfs
#=========================== Filebeat inputs =============================
filebeat.inputs:
################Log4j Logs#######################
- type: log
  enabled: true
  paths:
    - ${FILEBEAT_LOGS_DIR}/log4j/accountprovisioner.log
  multiline.pattern: '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|^(\d{2}-[a-zA-Z]{3}-\d{4})|^(\d{4}-\d{2}-\d{2})|^(\w+ [\s*\[]+\d{4}-\d{2}-\d{2})|^(\w+\s*[|][a-z0-9\s]*[|]\s*\d{4}\/\d{2}\/\d{2})|^([a-zA-Z]{3}\s\d{2}\s\d{2}:\d{2}:\d{2}:\d{3})|(\s{4}\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2} \[)|^\[(\d{2} [a-zA-Z]{3} \d{4})|^(\d{2}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2})'
  multiline.negate: true
  multiline.match: after
  tags: "{{ .Values.namespace }}-{{ .Values.appName }}"
  fields:
    logtype: "log4j"
  fields_under_root: true
  clean_removed: false
################Tomcat Error (Catalina) Logs#######################
- type: log
  enabled: true
  paths:
    - ${FILEBEAT_LOGS_DIR}/tomcat/catalina*
  multiline.pattern: '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)|^(\d{2}-[a-zA-Z]{3}-\d{4})|^(\d{4}-\d{2}-\d{2})'
  multiline.negate: true
  multiline.match: after
  tags: "{{ .Values.namespace}}-{{ .Values.appName}}"
  fields:
    logtype: "tomcat"
  fields_under_root: true
  clean_removed: false
#============================= Filebeat modules ===============================
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml
  # Set to true to enable config reloading
  reload.enabled: false
  # Period on which files under path should be checked for changes
  #reload.period: 10s
filebeat.registry.path: ${FILEBEAT_DATA_PATH}/registry
#==================== Elasticsearch template setting ==========================
setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false
#================================ General =====================================
fields:
  tenant_id: ${TENANT_ID:DEFAULTORG}
  ip: ${IP:127.0.0.1}
fields_under_root: true
queue:
  mem:
    # Max number of events the queue can buffer.
    events: 262144
    flush.min_events: 4096
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_BEATS_PORT}"]
  loadbalance: true
  bulk_max_size : 4096
  worker: 4
  pipelining: 4
#================================ Processors =====================================
# Configure processors to enhance or manipulate events generated by the beat.
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
#================================ Logging =====================================
logging.level: info
logging.to_files: true
logging.files:
  path: ${FILEBEAT_LOGGER_PATH}
  name: filebeat.log
  keepfiles: ${FILEBEAT_LOGGER_FILE_COUNT}
  rotateeverybytes: ${FILEBEAT_LOGGER_FILE_SIZE_IN_BYTE}